#!/bin/bash
set -eo pipefail

## Load slug from Bind Mount, URL or STDIN

export HOME=/app
mkdir -p $HOME

if [[ $(ls -A $HOME) ]]; then
	true
elif [[ $SLUG_URL ]]; then
	curl -m 30 --retry 2 -s -o /tmp/slug.tgz "$SLUG_URL"
	tar -xzf /tmp/slug.tgz -C $HOME
	rm /tmp/slug.tgz
	unset SLUG_URL
else
	cat | tar -xzC $HOME
fi
cd $HOME

## Load profile.d and release config

shopt -s nullglob
mkdir -p .profile.d
if [[ -s .release ]]; then
	ruby -e "require 'yaml';(YAML.load_file('.release')['config_vars'] || {}).each{|k,v| puts \"#{k}='#{v}'\"}" > .profile.d/config_vars
fi
for file in .profile.d/*; do
	source $file
done
hash -r

## Inject "start" command to run processes defined in Procfile

case "$1" in
	start)
		if [[ -f Procfile ]]; then
			command="$(ruby -e "require 'yaml';puts YAML.load_file('Procfile')['$2']")"
		else
			command="$(ruby -e "require 'yaml';puts (YAML.load_file('.release')['default_process_types'] || {})['$2']")"
		fi
		;;

	*)
		command="$@"
		;;
esac

runner="bash -c"

## Run!

exec $runner "$command"
